export interface WorldTimezone {
  abbreviation: string;
  countries: string[];
  name: string;
  utc: string;
}

export const worldTimezones: WorldTimezone[] = [
  {
    name: 'UTC-11',
    abbreviation: 'SST',
    utc: 'UTC-11:00',
    countries: ['American Samoa', 'Niue', 'U.S. Minor Outlying Islands'],
  },
  {
    name: 'Hawaiian Standard Time',
    abbreviation: 'HST',
    utc: 'UTC-10:00',
    countries: ['United States', 'Cook Islands', 'French Polynesia'],
  },
  {
    name: 'Pacific Standard Time',
    abbreviation: 'PST',
    utc: 'UTC-08:00',
    countries: ['United States', 'Canada', 'Pitcairn Islands'],
  },
  {
    name: 'Mountain Standard Time',
    abbreviation: 'MST',
    utc: 'UTC-07:00',
    countries: ['United States', 'Canada', 'Mexico'],
  },
  {
    name: 'Central Standard Time',
    abbreviation: 'CST',
    utc: 'UTC-06:00',
    countries: [
      'United States',
      'Canada',
      'Mexico',
      'Belize',
      'Costa Rica',
      'El Salvador',
      'Guatemala',
      'Honduras',
      'Nicaragua',
    ],
  },
  {
    name: 'Eastern Standard Time',
    abbreviation: 'EST',
    utc: 'UTC-05:00',
    countries: [
      'United States',
      'Canada',
      'Bahamas, The',
      'Cuba',
      'Haiti',
      'Turks and Caicos Islands',
      'Colombia',
      'Ecuador',
      'Jamaica',
      'Panama',
      'Peru',
      'Cayman Islands',
    ],
  },
  {
    name: 'Venezuela Standard Time',
    abbreviation: 'VET',
    utc: 'UTC-04:30',
    countries: ['Bolivarian Republic of Venezuela'],
  },
  {
    name: 'Atlantic Standard Time',
    abbreviation: 'AST',
    utc: 'UTC-04:00',
    countries: [
      'Canada',
      'Bermuda',
      'Paraguay',
      'Anguilla',
      'Antigua and Barbuda',
      'Aruba',
      'Barbados',
      'Bolivia',
      'Bonaire, Sint Eustatius and Saba',
      'Curaçao',
      'Dominica',
      'Dominican Republic',
      'Grenada',
      'Guadeloupe',
      'Guyana',
      'Martinique',
      'Montserrat',
      'Puerto Rico',
      'Saint Barthélemy',
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Saint Martin (French part)',
      'Saint Vincent and the Grenadines',
      'Sint Maarten (Dutch part)',
      'Trinidad and Tobago',
      'Virgin Islands, British',
      'Virgin Islands, U.S.',
    ],
  },
  {
    name: 'South America Standard Time',
    abbreviation: 'BRT',
    utc: 'UTC-03:00',
    countries: [
      'Argentina',
      'Brazil',
      'Chile',
      'Uruguay',
      'Antarctica',
      'Falkland Islands (Islas Malvinas)',
      'French Guiana',
      'Suriname',
      'Greenland',
      'Saint Pierre and Miquelon',
    ],
  },
  {
    name: 'UTC-02',
    abbreviation: 'GST',
    utc: 'UTC-02:00',
    countries: ['South Georgia and the South Sandwich Islands'],
  },
  {
    name: 'Cape Verde Standard Time',
    abbreviation: 'CVT',
    utc: 'UTC-01:00',
    countries: ['Cabo Verde'],
  },
  {
    name: 'Greenwich Mean Time',
    abbreviation: 'GMT',
    utc: 'UTC',
    countries: [
      'United Kingdom',
      'Ireland',
      'Portugal',
      'Iceland',
      'Morocco',
      'Faroe Islands',
      'Guernsey',
      'Jersey',
      'Man, Isle of',
      'Burkina Faso',
      "Côte d'Ivoire",
      'Gambia, The',
      'Ghana',
      'Guinea',
      'Guinea-Bissau',
      'Liberia',
      'Mali',
      'Mauritania',
      'Saint Helena, Ascension and Tristan da Cunha',
      'Senegal',
      'Sierra Leone',
      'São Tomé and Príncipe',
      'Togo',
      'Bouvet Island',
    ],
  },
  {
    name: 'Central European Time',
    abbreviation: 'CET',
    utc: 'UTC+01:00',
    countries: [
      'Germany',
      'France',
      'Italy',
      'Spain',
      'Poland',
      'Netherlands',
      'Belgium',
      'Czech Republic',
      'Austria',
      'Switzerland',
      'Hungary',
      'Slovakia',
      'Slovenia',
      'Croatia',
      'Serbia',
      'Bosnia and Herzegovina',
      'Montenegro',
      'Kosovo',
      'Macedonia, Former Yugoslav Republic of',
      'Albania',
      'Denmark',
      'Sweden',
      'Norway',
      'Luxembourg',
      'Liechtenstein',
      'Monaco',
      'San Marino',
      'Vatican City',
      'Malta',
      'Andorra',
      'Gibraltar',
      'Jan Mayen',
      'Svalbard',
      'Algeria',
      'Tunisia',
      'Morocco',
      'Angola',
      'Benin',
      'Cameroon',
      'Central African Republic',
      'Chad',
      'Congo',
      'Congo (DRC)',
      'Equatorial Guinea',
      'Gabon',
      'Niger',
      'Nigeria',
      'Namibia',
    ],
  },
  {
    name: 'Eastern European Time',
    abbreviation: 'EET',
    utc: 'UTC+02:00',
    countries: [
      'Finland',
      'Estonia',
      'Latvia',
      'Lithuania',
      'Poland',
      'Czech Republic',
      'Slovakia',
      'Hungary',
      'Romania',
      'Bulgaria',
      'Greece',
      'Turkey',
      'Cyprus',
      'Ukraine',
      'Moldova',
      'Belarus',
      'Russia',
      'Egypt',
      'Libya',
      'Israel',
      'Palestinian Authority',
      'Jordan',
      'Lebanon',
      'Syria',
      'South Africa',
      'Botswana',
      'Zimbabwe',
      'Zambia',
      'Malawi',
      'Mozambique',
      'Swaziland',
      'Lesotho',
      'Burundi',
      'Rwanda',
      'Åland Islands',
    ],
  },
  {
    name: 'Moscow Standard Time',
    abbreviation: 'MSK',
    utc: 'UTC+03:00',
    countries: [
      'Russia',
      'Belarus',
      'Bahrain',
      'Kuwait',
      'Qatar',
      'Saudi Arabia',
      'Yemen',
      'Iraq',
      'Comoros',
      'Djibouti',
      'Eritrea',
      'Ethiopia',
      'Kenya',
      'Madagascar',
      'Mayotte',
      'Somalia',
      'South Sudan',
      'Sudan',
      'Tanzania',
      'Uganda',
    ],
  },
  {
    name: 'Iran Standard Time',
    abbreviation: 'IRST',
    utc: 'UTC+03:30',
    countries: ['Iran'],
  },
  {
    name: 'Gulf Standard Time',
    abbreviation: 'GST',
    utc: 'UTC+04:00',
    countries: [
      'United Arab Emirates',
      'Oman',
      'Azerbaijan',
      'Armenia',
      'Georgia',
      'Mauritius',
      'Reunion',
      'Seychelles',
      'Heard Island and McDonald Islands',
    ],
  },
  {
    name: 'Afghanistan Standard Time',
    abbreviation: 'AFT',
    utc: 'UTC+04:30',
    countries: ['Afghanistan'],
  },
  {
    name: 'Pakistan Standard Time',
    abbreviation: 'PKT',
    utc: 'UTC+05:00',
    countries: [
      'Pakistan',
      'Uzbekistan',
      'Turkmenistan',
      'Tajikistan',
      'Maldives',
      'French Southern and Antarctic Lands',
    ],
  },
  {
    name: 'India Standard Time',
    abbreviation: 'IST',
    utc: 'UTC+05:30',
    countries: ['India', 'Sri Lanka'],
  },
  {
    name: 'Nepal Standard Time',
    abbreviation: 'NPT',
    utc: 'UTC+05:45',
    countries: ['Nepal'],
  },
  {
    name: 'Bangladesh Standard Time',
    abbreviation: 'BST',
    utc: 'UTC+06:00',
    countries: [
      'Bangladesh',
      'Bhutan',
      'Kazakhstan',
      'Kyrgyzstan',
      'British Indian Ocean Territory',
    ],
  },
  {
    name: 'Myanmar Standard Time',
    abbreviation: 'MMT',
    utc: 'UTC+06:30',
    countries: ['Myanmar', 'Cocos (Keeling) Islands'],
  },
  {
    name: 'Southeast Asia Standard Time',
    abbreviation: 'ICT',
    utc: 'UTC+07:00',
    countries: [
      'Thailand',
      'Vietnam',
      'Cambodia',
      'Laos',
      'Indonesia',
      'Christmas Island',
    ],
  },
  {
    name: 'China Standard Time',
    abbreviation: 'CST',
    utc: 'UTC+08:00',
    countries: [
      'China',
      'Taiwan',
      'Hong Kong SAR',
      'Macao SAR',
      'Singapore',
      'Malaysia',
      'Philippines',
      'Brunei',
      'Mongolia',
    ],
  },
  {
    name: 'Japan Standard Time',
    abbreviation: 'JST',
    utc: 'UTC+09:00',
    countries: [
      'Japan',
      'Korea',
      'North Korea',
      'Democratic Republic of Timor-Leste',
      'Palau',
    ],
  },
  {
    name: 'Australia Eastern Standard Time',
    abbreviation: 'AEST',
    utc: 'UTC+10:00',
    countries: [
      'Australia',
      'Papua New Guinea',
      'Guam',
      'Northern Mariana Islands',
      'Micronesia',
    ],
  },
  {
    name: 'Central Pacific Standard Time',
    abbreviation: 'SBT',
    utc: 'UTC+11:00',
    countries: [
      'Solomon Islands',
      'Vanuatu',
      'New Caledonia',
      'Norfolk Island',
    ],
  },
  {
    name: 'New Zealand Standard Time',
    abbreviation: 'NZST',
    utc: 'UTC+12:00',
    countries: [
      'New Zealand',
      'Fiji Islands',
      'Kiribati',
      'Marshall Islands',
      'Nauru',
      'Tuvalu',
      'Wallis and Futuna',
    ],
  },
  {
    name: 'Pacific Island Time',
    abbreviation: 'TOT',
    utc: 'UTC+13:00',
    countries: ['Tonga', 'Samoa', 'Tokelau'],
  },
];
